### ISSUE TITLE
Donation suggestions

### ISSUE THREAD

**Issue by PonyoBear** [lexikiq/minecraft-crowdcontrol#1]
!gamemode - sets their gamemode
!xp <level> - sets their xp level
!hat <item> - sets that item as their hat

**Comment by poppyisalive** [comment]
!take <amount> - take but for multiple items!

**Comment by lexikiq** [comment]
good suggestions, will implement in v2.0.0 :)

xp would be based on the number of bits donated i imagine (0-100?), same with the count of items removed by !take

for xp and gamemode, those could just be fixed donation amounts, ie you don't actually have to type "!xp" but instead just donate an exact amount. for gamemodes it could be 125 bits for survival, 150 for creative, 175 for spectator, 200 for adventure. ideally they'll all be configurable as well (which is my main goal for the v2 update: let people set the amount for each command. it can either be chat cooldowns, donation totals, etc)

some other ideas i have include teleporting every mob on the server to the players (~$100/10,000 bits), teleporting every player to the end ($500/5,000 bits), giving/taking stacks of some items ($5 for a stack of golden apples, $6 to take away, $10 for enchanted apples, $11 to take away)

i also plan to implement channel points, not sure of any commands to set to it by default though.

**Comment by lexikiq** [comment]
Will be implementing proper integration with the [Crowd Control](https://crowdcontrol.live) app soon, suggestions will be tracked in #2 (as i don't like editing others' comments :P)

**Comment by qixils** [comment]
these commands have been added :)
